
env:
   global:
     - CONAN_USERNAME: "darcamo"
     - CONAN_LOGIN_USERNAME: "darcamo"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/darcamo/cppsim"
     - CONAN_BUILD_POLICY: "outdated"
     - CONAN_ARCHS: "x86_64"
     - CONAN_TOTAL_PAGES: 4


linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=10 CONAN_DOCKER_IMAGE=conanio/gcc10 CONAN_BUILD_TYPES=Release
      - <<: *linux
        env: CONAN_GCC_VERSIONS=10 CONAN_DOCKER_IMAGE=conanio/gcc10 CONAN_BUILD_TYPES=Debug
      # - <<: *linux
      #   env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9 CONAN_BUILD_TYPES=Release
      # - <<: *linux
      #   env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9 CONAN_BUILD_TYPES=Debug
      # - <<: *linux
      #   env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 CONAN_BUILD_TYPES=Release
      # - <<: *linux
      #   env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 CONAN_BUILD_TYPES=Debug

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=10 CONAN_DOCKER_IMAGE=conanio/clang10 CONAN_BUILD_TYPES=Release
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=10 CONAN_DOCKER_IMAGE=conanio/clang10 CONAN_BUILD_TYPES=Debug
      # - <<: *linux
      #   env: CONAN_CLANG_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/clang9 CONAN_BUILD_TYPES=Release
      # - <<: *linux
      #   env: CONAN_CLANG_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/clang9 CONAN_BUILD_TYPES=Debug
      # - <<: *linux
      #   env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8 CONAN_BUILD_TYPES=Release
      # - <<: *linux
      #   env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8 CONAN_BUILD_TYPES=Debug

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
